#!/bin/bash
set -euo pipefail

LOG_DIR="/var/log"
REPORT="log-report-$(date +%Y%m%d).txt"

echo "=== Log Analyzer Report - $(date) ===" > "$REPORT"
echo "Generated by: $(whoami) @ $(hostname)" >> "$REPORT"
echo "==========================================" >> "$REPORT"

echo "[1] Last 10 auth failures:" >> "$REPORT"
grep "Failed password" "$LOG_DIR/auth.log" 2>/dev/null | tail -10 >> "$REPORT" || echo "No auth.log found" >> "$REPORT"

echo -e "\n[2] Top 10 error keywords in syslog:" >> "$REPORT"
grep -iE "(error|fail|warning|critical)" "$LOG_DIR/syslog" 2>/dev/null | cut -d' ' -f5- | sort | uniq -c | sort -nr | head -10 >> "$REPORT" || true

echo -e "\n[3] Disk usage of log files:" >> "$REPORT"
du -h "$LOG_DIR"/*.log 2>/dev/null | sort -hr | head -10 >> "$REPORT" || true

echo -e "\nReport saved to: $REPORT"
cat "$REPORT"
