name: Backup API - Secure CI/CD

on:
  push:
    paths: ['microservice/backup/**']
  pull_request:
    paths: ['microservice/backup/**']

jobs:
  build-sign-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y buildah
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Build Image
        run: cd microservice/backup/docker && ./build.sh

      - name: Generate SBOM
        run: syft localhost/backup-api:v1.0.0 -o cyclonedx-json > sbom-backup.json

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localhost/backup-api:v1.0.0
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Sign with Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-version: 'v2.2.1'
      - run: cosign sign --yes localhost/backup-api:v1.0.0

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
