apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: devops-platform
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
