apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/managed-by: day27-argocd
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
